/**
 * CXC-Loader - Loader Data
 * Contains metadata for all available loaders
 */

const loaderData = [
    {
        id: "grid-perimeter",
        category: "grid",
        name: "Perimeter Blink",
        tag: "G-013",
        createdAt: "2023-06-22",
        totalIndex: 1,
    },
    {
        id: "grid-step",
        category: "grid",
        name: "Step Flash",
        tag: "G-012",
        createdAt: "2023-06-21",
        totalIndex: 2,
    },
    {
        id: "grid-wave",
        category: "grid",
        name: "Wave Sweep",
        tag: "G-011",
        createdAt: "2023-06-20",
        totalIndex: 3,
    },
    {
        id: "grid-revCol",
        category: "grid",
        name: "Reverse Col",
        tag: "G-010",
        createdAt: "2023-06-19",
        totalIndex: 4,
    },
    {
        id: "grid-revRow",
        category: "grid",
        name: "Reverse Row",
        tag: "G-009",
        createdAt: "2023-06-18",
        totalIndex: 5,
    },
    {
        id: "grid-center",
        category: "grid",
        name: "Center Out",
        tag: "G-008",
        createdAt: "2023-06-17",
        totalIndex: 6,
    },
    {
        id: "grid-col",
        category: "grid",
        name: "Column Pulse",
        tag: "G-007",
        createdAt: "2023-06-16",
        totalIndex: 7,
    },
    {
        id: "grid-row",
        category: "grid",
        name: "Row Pulse",
        tag: "G-006",
        createdAt: "2023-06-15",
        totalIndex: 8,
    },
    {
        id: "grid-spiral",
        category: "grid",
        name: "Spiral Inward",
        tag: "G-005",
        createdAt: "2023-06-14",
        totalIndex: 9,
    },
    {
        id: "grid-diag",
        category: "grid",
        name: "Diagonal Sweep",
        tag: "G-004",
        createdAt: "2023-06-13",
        totalIndex: 10,
    },
    {
        id: "grid-flicker",
        category: "grid",
        name: "Grid Flicker",
        tag: "G-003",
        createdAt: "2023-06-12",
        totalIndex: 11,
    },
    {
        id: "grid-breathing",
        category: "grid",
        name: "Breathing Center",
        tag: "G-002",
        createdAt: "2023-06-11",
        totalIndex: 12,
    },
    {
        id: "grid-flow",
        category: "grid",
        name: "Grid Flow",
        tag: "G-001",
        createdAt: "2023-06-10",
        totalIndex: 13,
    },
    {
        id: "jelly-fractal",
        category: "jelly",
        name: "Jelly Fractal",
        tag: "J-002",
        createdAt: "2023-06-09",
        totalIndex: 4,
    },
    {
        id: "synaptic-pulse",
        category: "synaptic",
        name: "Synaptic Pulse",
        tag: "SY-001",
        createdAt: "2023-06-08",
        totalIndex: 1,
    },
    {
        id: "tail-blink",
        category: "tail",
        name: "Tail Blink",
        tag: "T-001",
        createdAt: "2023-06-07",
        totalIndex: 2,
    },
    {
        id: "ripple-portal",
        category: "ripple",
        name: "Portal Ripple",
        tag: "R-003",
        createdAt: "2023-06-06",
        totalIndex: 3,
    },
    {
        id: "particle-flow",
        category: "particle",
        name: "Particle Flow",
        tag: "PA-001",
        createdAt: "2023-06-05",
        totalIndex: 4,
    },
    {
        id: "jelly-merge",
        category: "jelly",
        name: "Jelly Merge",
        tag: "J-001",
        createdAt: "2023-06-04",
        totalIndex: 5,
    },
    {
        id: "ripple-soft",
        category: "ripple",
        name: "Soft Ripple",
        tag: "R-002",
        createdAt: "2023-06-03",
        totalIndex: 6,
    },
    {
        id: "pulse-particle-converge",
        category: "pulse",
        name: "Particle Converge",
        tag: "P-004",
        createdAt: "2023-06-02",
        totalIndex: 7,
    },
    {
        id: "pulse-whisper-float",
        category: "pulse",
        name: "Whisper Float",
        tag: "P-003",
        createdAt: "2023-06-01",
        totalIndex: 8,
    },
    {
        id: "ripple-basic",
        category: "ripple",
        name: "Basic Ripple",
        tag: "R-001", // R for Ripple
        createdAt: "2023-05-25",
        totalIndex: 9,
    },
    {
        id: "progress-bar",
        category: "progress",
        name: "Progress Bar",
        tag: "PB-001", // PB for Progress Bar
        createdAt: "2023-05-24",
        totalIndex: 10,
    },
    {
        id: "dots-fade",
        category: "dots",
        name: "Fading Dots",
        tag: "D-003",
        createdAt: "2023-05-23",
        totalIndex: 11,
    },
    {
        id: "dots-bounce",
        category: "dots",
        name: "Bouncing Dots",
        tag: "D-002",
        createdAt: "2023-05-22",
        totalIndex: 12,
    },
    {
        id: "dots-basic",
        category: "dots",
        name: "Basic Dots",
        tag: "D-001",
        createdAt: "2023-05-21",
        totalIndex: 13,
    },
    {
        id: "pulse-wave",
        category: "pulse",
        name: "Wave Pulse",
        tag: "P-002",
        createdAt: "2023-05-19",
        totalIndex: 14,
    },
    {
        id: "pulse-basic",
        category: "pulse",
        name: "Basic Pulse",
        tag: "P-001", // P for Pulse
        createdAt: "2023-05-18",
        totalIndex: 15,
    },
    {
        id: "spinner-triple",
        category: "spinner",
        name: "Triple Spinner",
        tag: "S-003",
        createdAt: "2023-05-17",
        totalIndex: 16,
    },
    {
        id: "spinner-dual",
        category: "spinner",
        name: "Dual Spinner",
        tag: "S-002",
        createdAt: "2023-05-16",
        totalIndex: 17,
    },
    {
        id: "spinner-basic",
        category: "spinner",
        name: "Basic Spinner",
        tag: "S-001", // S for Spinner, 001 is the first in Spinner category
        createdAt: "2023-05-15", // Creation date (for sorting)
        totalIndex: 18, // Overall index across all loaders
    },
];
