/**
 * CXC-Loader - Loader Data
 * Contains metadata for all available loaders
 */

const loaderData = [
    {
        id: "fluid-liquid",
        category: "fluid",
        name: "Liquid Sphere",
        tag: "F-004",
        createdAt: "2024-07-14",
        totalIndex: 1,
    },
    {
        id: "wave-audio",
        category: "wave",
        name: "Audio Wave",
        tag: "W-003",
        createdAt: "2024-07-12",
        totalIndex: 4,
    },
    {
        id: "wave-ripple",
        category: "wave",
        name: "Ripple Wave",
        tag: "W-002",
        createdAt: "2024-07-11",
        totalIndex: 5,
    },
    {
        id: "wave-oscillate",
        category: "wave",
        name: "Oscillate Wave",
        tag: "W-001",
        createdAt: "2024-07-07",
        totalIndex: 6,
    },

    {
        id: "spinner-bubble-pulse",
        category: "pulse",
        name: "Bubble Pulse",
        tag: "P-008",
        createdAt: "2024-07-04",
        totalIndex: 2,
    },
    {
        id: "spinner-siri-wave",
        category: "wave",
        name: "Siri Wave",
        tag: "W-007",
        createdAt: "2024-07-03",
        totalIndex: 7,
    },
    {
        id: "spinner-circular",
        category: "spinner",
        name: "Circular Spinner",
        tag: "S-004",
        createdAt: "2024-06-28",
        totalIndex: 1,
    },
    {
        id: "progress-segments",
        category: "progress",
        name: "Segmented Progress",
        tag: "PB-002",
        createdAt: "2024-06-27",
        totalIndex: 2,
    },
    {
        id: "grid-perimeter",
        category: "grid",
        name: "Perimeter Blink",
        tag: "G-013",
        createdAt: "2023-06-22",
        totalIndex: 3,
    },
    {
        id: "grid-step",
        category: "grid",
        name: "Step Flash",
        tag: "G-012",
        createdAt: "2023-06-21",
        totalIndex: 4,
    },
    {
        id: "grid-wave",
        category: "grid",
        name: "Wave Sweep",
        tag: "G-011",
        createdAt: "2023-06-20",
        totalIndex: 5,
    },
    {
        id: "grid-revCol",
        category: "grid",
        name: "Reverse Col",
        tag: "G-010",
        createdAt: "2023-06-19",
        totalIndex: 6,
    },
    {
        id: "grid-revRow",
        category: "grid",
        name: "Reverse Row",
        tag: "G-009",
        createdAt: "2023-06-18",
        totalIndex: 7,
    },
    {
        id: "grid-center",
        category: "grid",
        name: "Center Out",
        tag: "G-008",
        createdAt: "2023-06-17",
        totalIndex: 8,
    },
    {
        id: "grid-col",
        category: "grid",
        name: "Column Pulse",
        tag: "G-007",
        createdAt: "2023-06-16",
        totalIndex: 9,
    },
    {
        id: "grid-row",
        category: "grid",
        name: "Row Pulse",
        tag: "G-006",
        createdAt: "2023-06-15",
        totalIndex: 10,
    },
    {
        id: "grid-spiral",
        category: "grid",
        name: "Spiral Inward",
        tag: "G-005",
        createdAt: "2023-06-14",
        totalIndex: 11,
    },
    {
        id: "grid-diag",
        category: "grid",
        name: "Diagonal Sweep",
        tag: "G-004",
        createdAt: "2023-06-13",
        totalIndex: 12,
    },
    {
        id: "grid-flicker",
        category: "grid",
        name: "Grid Flicker",
        tag: "G-003",
        createdAt: "2023-06-12",
        totalIndex: 13,
    },
    {
        id: "grid-breathing",
        category: "grid",
        name: "Breathing Center",
        tag: "G-002",
        createdAt: "2023-06-11",
        totalIndex: 14,
    },
    {
        id: "grid-flow",
        category: "grid",
        name: "Grid Flow",
        tag: "G-001",
        createdAt: "2023-06-10",
        totalIndex: 15,
    },
    {
        id: "jelly-fractal",
        category: "fluid",
        name: "Jelly Fractal",
        tag: "F-003",
        createdAt: "2023-06-09",
        totalIndex: 16,
    },
    {
        id: "synaptic-pulse",
        category: "dots",
        name: "Synaptic Pulse",
        tag: "D-004",
        createdAt: "2023-06-08",
        totalIndex: 17,
    },
    {
        id: "tail-blink",
        category: "dots",
        name: "Tail Blink",
        tag: "D-005",
        createdAt: "2023-06-07",
        totalIndex: 18,
    },
    {
        id: "ripple-portal",
        category: "pulse",
        name: "Portal Ripple",
        tag: "P-005",
        createdAt: "2023-06-06",
        totalIndex: 19,
    },
    {
        id: "particle-flow",
        category: "dots",
        name: "Particle Flow",
        tag: "D-006",
        createdAt: "2023-06-05",
        totalIndex: 20,
    },
    {
        id: "jelly-merge",
        category: "fluid",
        name: "Jelly Merge",
        tag: "F-002",
        createdAt: "2023-06-04",
        totalIndex: 21,
    },
    {
        id: "ripple-soft",
        category: "pulse",
        name: "Soft Ripple",
        tag: "P-006",
        createdAt: "2023-06-03",
        totalIndex: 22,
    },
    {
        id: "pulse-particle-converge",
        category: "particle",
        name: "Particle Converge",
        tag: "PA-004",
        createdAt: "2023-06-02",
        totalIndex: 23,
    },
    {
        id: "pulse-whisper-float",
        category: "particle",
        name: "Whisper Float",
        tag: "PA-005",
        createdAt: "2023-06-01",
        totalIndex: 24,
    },
    {
        id: "ripple-basic",
        category: "pulse",
        name: "Basic Ripple",
        tag: "P-007", // Now P for Pulse
        createdAt: "2023-05-25",
        totalIndex: 25,
    },
    {
        id: "progress-bar",
        category: "progress",
        name: "Progress Bar",
        tag: "PB-001", // PB for Progress Bar
        createdAt: "2023-05-24",
        totalIndex: 26,
    },
    {
        id: "dots-fade",
        category: "dots",
        name: "Fading Dots",
        tag: "D-003",
        createdAt: "2023-05-23",
        totalIndex: 27,
    },
    {
        id: "dots-bounce",
        category: "dots",
        name: "Bouncing Dots",
        tag: "D-002",
        createdAt: "2023-05-22",
        totalIndex: 28,
    },
    {
        id: "dots-basic",
        category: "dots",
        name: "Basic Dots",
        tag: "D-001",
        createdAt: "2023-05-21",
        totalIndex: 29,
    },
    {
        id: "pulse-wave",
        category: "pulse",
        name: "Wave Pulse",
        tag: "P-002",
        createdAt: "2023-05-19",
        totalIndex: 30,
    },
    {
        id: "pulse-basic",
        category: "pulse",
        name: "Basic Pulse",
        tag: "P-001", // P for Pulse
        createdAt: "2023-05-18",
        totalIndex: 31,
    },
    {
        id: "spinner-triple",
        category: "spinner",
        name: "Triple Spinner",
        tag: "S-003",
        createdAt: "2023-05-17",
        totalIndex: 32,
    },
    {
        id: "spinner-dual",
        category: "spinner",
        name: "Dual Spinner",
        tag: "S-002",
        createdAt: "2023-05-16",
        totalIndex: 33,
    },
    {
        id: "spinner-basic",
        category: "spinner",
        name: "Basic Spinner",
        tag: "S-001", // S for Spinner, 001 is the first in Spinner category
        createdAt: "2023-05-15", // Creation date (for sorting)
        totalIndex: 34, // Overall index across all loaders
    },
];
